### ISSUE TITLE
Is Tg(elavl3: H2B-RFP) template available? 

### ISSUE THREAD

**Issue by danustc** [owenrandlett/Z-Brain#5]
Hi Z-Brain developers, 

I would like to register SPIM images of my Tg(elavl3:H2B-GCaMP6s) fish to the Z-brain template for anatomical annotation, since the signals are from neuronal nuclei, the anti-tERK template provided on the Z-Brain website would not work for the intensity-based registration. I was wondering if the Tg(elavl3:H2B-RFP) reference brain (used in the eLife paper for registering the Tg(elavl3:H2B-GCaMP6f) images ) could be provided. Thanks! 

Dan

**Comment by owenrandlett** [comment]
Hi Dan, 

Yes for sure, you can get it from the HDF5 file on the Z-Brain website. 

http://engertlab.fas.harvard.edu/Z-Brain/zDownloads/AnatomyLabelDatabase.hdf5

Just to clarify. In the eLife paper, we used essentially a two reference brain/bridging brain strategy for the light sheet registrations. We first registered all the light sheet data into a light sheet brain, then registered the average signal of all of these brains into the Tg(elavl3:H2B-RFP) reference brain. I can also give you that light sheet reference brain we used. But, I think it might be better if you try something similar -- register all of your light sheet data into a common reference brain (which will have all of the particulars of your specific microscope in common, and thus should be relatively easy), then try the cross-modal registration into the Z-Brain, which is more difficult, but only has to be done once for all of your data.

**Comment by danustc** [comment]
Thanks! Yes, it would be quite helpful if we can have the light-sheet reference brain. Is your light-sheet imaging path consistent with that in confocal/2-photon? Since my SPIM images are acquired from a ~50 degree angle w.r.t. to the z-direction while the fish is lying dorsal up, I may have to resample my image stacks so that they can be represented the same way as those acquired from the upright direction.

**Comment by owenrandlett** [comment]
Hi Dan, 

Sorry for the delay - you can get the light-sheet HuC:H2BGCaMP reference brain here: https://www.dropbox.com/s/cyiaramrkbg83gh/a-flpLR-cy74-LS_01.nrrd?dl=0

The imaging path is consistent with confocal/2-photon - detection objective pointed at the dorsal surface of the brain. I am not sure what strategy you are using for the registraiton, but I would hope that dealing with a 50-degree tilt shouldnt be too big of an issue. But lighting artifacts might substantially different and become a concern -- like shadowing over the eyes. So I still think that its worth thinking about first aggregating all of your specific data together, and then figuring out how to get it all into Z-Brain in one step.
