### ISSUE TITLE
Issue with ZBrainAnalysisOfMAPMaps.m

### ISSUE THREAD

**Issue by rachellac** [owenrandlett/Z-Brain#7]
Hello, I was hoping you could help me with this issue. When trying to run the Z Brain Analysis on Matlab I get this error:

>> ZBrainAnalysisOfMAPMaps
Not enough input arguments.

Error in height (line 10)
H = size(X,1);

Error in ZBrainAnalysisOfMAPMaps>MakeDownsampledFiles (line 645)
    MaskTemp = reshape(full(MaskDatabase(:,n)), [height, width, Zs]);

Error in ZBrainAnalysisOfMAPMaps (line 145)
        MakeDownsampledFiles(MaskDatabasePath); % if we dont aready have the downsampled database, make it.
 
How can I fix this to run the script?

**Comment by owenrandlett** [comment]
are you seeing the prompts in order point you towards the files? Do you have the AnatomyDabase.hdf5 and MaskDatabase.mat files?
